kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# This is an additional configuration to set the api server listen address and port
# It is useful when exposing the api server over the network
#networking:
#  apiServerAddress: "0.0.0.0"
#  apiServerPort: 6443
nodes:
  - role: worker
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ${HOME}/.docker/config.json
        readOnly: true
  - role: worker
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ${HOME}/.docker/config.json
        readOnly: true
  - role: worker
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ${HOME}/.docker/config.json
        readOnly: true
  - role: control-plane
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ${HOME}/.docker/config.json
        readOnly: true
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      # This is an additional configuration to set the api server certificate SANs
      # It is useful when exposing the api server over the network
      #- |
      #  kind: ClusterConfiguration
      #  apiServer:
      #    certSANs:
      #      - "api.yourdomain"
      #      - "0.0.0.0"
      #      - "localhost"
    extraPortMappings:
      # port t obe used by ingress-nginx to expose http and https
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      # Ports to be used by ingress-nginx to expose TCP protocols like mariadb
      - containerPort: 33060
        hostPort: 33060
        protocol: TCP
      - containerPort: 33061
        hostPort: 33061
        protocol: TCP
      - containerPort: 33062
        hostPort: 33062
        protocol: TCP
      - containerPort: 33063
        hostPort: 33063
        protocol: TCP
      - containerPort: 33064
        hostPort: 33064
        protocol: TCP
      - containerPort: 33065
        hostPort: 33065
        protocol: TCP
      # Ports to be used by ingress-nginx to expose TCP protocols like artemis acceptors
      - containerPort: 51510
        hostPort: 51510
        protocol: TCP
      - containerPort: 51511
        hostPort: 51511
        protocol: TCP
      - containerPort: 51512
        hostPort: 51512
        protocol: TCP
      - containerPort: 51513
        hostPort: 51513
        protocol: TCP
      - containerPort: 51514
        hostPort: 51514
        protocol: TCP
      # Ports to be used by ingress-nginx to expose TCP protocols like java remote debbuger
      - containerPort: 5000
        hostPort: 5000
        protocol: TCP
      - containerPort: 5001
        hostPort: 5001
        protocol: TCP
      - containerPort: 5002
        hostPort: 5002
        protocol: TCP
      - containerPort: 5003
        hostPort: 5003
        protocol: TCP
      - containerPort: 5004
        hostPort: 5004
        protocol: TCP

