apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-bundle
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: "selfsigned-ca-root-secret-copy"
      key: "tls.crt"
  target:
    configMap:
      key: "trust-bundle.pem"
    secret:
      key: "trust-bundle.pem"
    additionalFormats:
      jks:
        key: "truststore.jks"