apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ClusterIssuer-selfsigned-cluster-issuer.yaml
  - Certificate-selfsigned-ca.yaml
  - ClusterIssuer-ca-issuer.yaml

