apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb
sortOptions:
  order: fifo
resources:
  - Namespace.yaml
  - MariaDB.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: mariadb-root
    literals:
      - password=root_mariadb

