apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: artemis
spec:
  mariaDbRef:
    name: mariadb
  privileges:
     - "ALL PRIVILEGES"
  database: "artemis"
  table: "*"
  username: artemis
  grantOption: false
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s

