apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb
sortOptions:
  order: fifo
resources:
  - Database.yaml
  - User.yaml
  - Grant.yaml
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: artemis-db-user
  literals:
  - password=artemis_mariadb

