apiVersion: v1
kind: Secret
metadata:
  name: 02-mirror-bp
stringData:
  broker.properties: |
    AMQPConnections.west.uri=tcp://artemis-west-amqp-${STATEFUL_SET_ORDINAL}-svc.artemis-west.svc.cluster.local:61611
    AMQPConnections.west.retryInterval=5000
    AMQPConnections.west.user=admin
    AMQPConnections.west.password=admin
    AMQPConnections.west.connectionElements.mirror.type=MIRROR
    AMQPConnections.west.connectionElements.mirror.sync=false
    AMQPConnections.west.connectionElements.mirror.messageAcknowledgements=true
    AMQPConnections.west.connectionElements.mirror.queueCreation=true
    AMQPConnections.west.connectionElements.mirror.queueRemoval=true
  broker-0: