apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: artemis-east
sortOptions:
  order: fifo
resources:
  - ../../base
  - 01-service-debugger-svc.yaml
  - 02-secret-01-base-bp.yaml
  - 03-secret-02-mirror-bp.yaml
  - 04-configmap-custom-logging-config.yaml
  - 05-activemqartemis-artemis-east.yaml

