apiVersion: v1
kind: Service
metadata:
  name: debugger-svc-peer-b
spec:
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
  publishNotReadyAddresses: false
  selector:
        statefulset.kubernetes.io/pod-name: artemis-peer-b-ss-0
  sessionAffinity: None
  type: ClusterIP