apiVersion: v1
kind: Secret
metadata:
  name: 02-jdbc-bp
stringData:
  broker.properties: |
    storeConfiguration=DATABASE
    storeConfiguration.jdbcDriverClassName=org.mariadb.jdbc.Driver
    storeConfiguration.jdbcConnectionUrl=jdbc:mariadb://mariadb.mariadb.svc.cluster.local:3306/artemis
    storeConfiguration.jdbcUser=artemis
    storeConfiguration.jdbcPassword=artemis_mariadb
    HAPolicyConfiguration=SHARED_STORE_PRIMARY
  broker-0: