apiVersion: v1
kind: Service
metadata:
  name: acceptor-ha-svc
spec:
  ports:
  - port: 61620
    protocol: TCP
    targetPort: 61610
  publishNotReadyAddresses: true
  selector:
    cluster: jdbc-ha
  sessionAffinity: None
  type: ClusterIP