apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: artemis-jdbc-shared-store
sortOptions:
  order: fifo
resources:
  - ../../base
  - 01-service-debugger-svc-peer-a.yaml
  - 02-service-debugger-svc-peer-b.yaml
  - 03-secret-01-base-bp.yaml
  - 04-secret-02-jdbc-bp.yaml
  - 05-configmap-custom-logging-config-peer-a.yaml
  - 06-configmap-custom-logging-config-peer-b.yaml
  - 07-service-acceptor-ha-svc.yaml
  - 08-service-jdbc-ha-ping-svc.yaml
  - 09-activemqartemis-artemis-peer-a.yaml
  - 10-activemqartemis-artemis-peer-b.yaml

