---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - 'releases/*.*.*'
    branches:
      - 'releases/*.*.*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Determine version
        id: version
        run: |
          REF="${GITHUB_REF_NAME#releases/}"
          echo "VERSION=${REF}" >> $GITHUB_ENV
      - name: Create release
        run: |
          set -x -e -o pipefail
          REPO_URL="https://api.github.com/repos/${{ github.repository }}"

          RELEASE_ID=$(curl -L -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$REPO_URL/releases/tags/${{ env.VERSION }}" | jq -r '.id')

          if [ -n "$RELEASE_ID" ]; then
            curl -L -X DELETE -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "$REPO_URL/releases/${RELEASE_ID}"
          fi

          curl -L -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$REPO_URL/releases" \
            -d "$(jq -c -n --arg tag_name "${{ env.VERSION }}" \
            --arg ref "${GITHUB_SHA}" \
            '{"tag_name":$tag_name,"generate_release_notes":true,"target_commitish":$ref}')"
